server:
  port: 8081

spring:
  application:
    # 应用名称
    name: @artifactId@
  profiles:
    # 环境配置
    active: @active@
  cloud:
    nacos:
      discovery:
        # 解决获取IP为内网，一般微服务采用内网安全性、可用性高
        # ip: 127.0.0.1
        # 服务注册地址
        server-addr: ${NACOS_HOST:twelvet-nacos}:${NACOS_PORT:8848}
        namespace: @nacos.namespace@
      config:
        #配置中心地址
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - nacos:twelvet-app-@active@.yml
      - nacos:${spring.application.name}-@active@.yml
#      config:
#        # 配置中心地址
#        server-addr: ${spring.cloud.nacos.discovery.server-addr}
#        # 配置文件格式
#        file-extension: yml
#        # 命名空间
#        namespace: @nacos.namespace@
#        # 配置组
#        group: DEFAULT_GROUP
#        # 共享配置
#        shared-configs:
#          - data-id: twelvet-app-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
