name: 'sync-repository'

on:
  workflow_dispatch:
  schedule:
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天0点0分（16+8=24点整）
    - cron: '00 16 * * *'

jobs:
  gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/twelvet-projects
          dst: gitee/twelvet
          dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          # 指定同步仓库
          static_list: twelvet,twelvet-ui,twelvet-fast,netty-websocket-spring-boot-starter,gins,twelvet-ai,twelvet-mall-ui,twelvet-mall,excel-spring-boot-starter,xss-spring-boot-starter,oss-spring-boot-starter,idempotent-spring-boot-starter
          force_update: true
          # 设置源仓库类型为组织：org，个人：user
          account_type: org
          clone_style: ssh
          debug: true

#   gitlab:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Mirror the Github organization repos to gitlab.
#         uses: Yikun/hub-mirror-action@master
#         with:
#           src: github/twelvet-projects
#           dst: gitlab/twelvet
#           dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
#           dst_token: ${{ secrets.GITEE_TOKEN }}
#           # static_list: "twelvet"
#           force_update: true
#           account_type: user
#           clone_style: ssh
#           debug: true
